server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Edu19-94
    url: jdbc:mysql://localhost:3306/payments
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: paymentService
  config:
    import: configserver:http://localhost:9296



  management:
    tracing:
      sampling:
        probability: 1.0
